services:
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr_goose
    ports:
      - "801:80"

  mysqldb:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass

  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3002:3000"
    volumes:
      - ./repos:/var/www/git
